name: 🚀 Feature Request
description: Request a new feature or enhancement
title: "[FEATURE] "
labels: ["feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the new feature.
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story / Use Case
      description: Help us understand who would benefit from this feature and how.
      placeholder: "As a [role], I want [feature] so that [benefit]."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional context, screenshots, references, or links that might be helpful.
      placeholder: Optional additional information...
    validations:
      required: false
